### ISSUE TITLE
Invalid JSON payload

### ISSUE THREAD

**Issue by Kikobeats** [amio/marked#2]
Awesome microservice!

I'm trying to send text content, but all requests finish with a 

![screen shot 2017-10-10 at 10 56 45](https://user-images.githubusercontent.com/2096101/31377854-bd0bf6fa-ada9-11e7-87e6-8f7b68eead38.png)

```
JSON body could not be parsed: Invalid JSON
```

What I'm doing wrong?

**Comment by amio** [comment]
You need to send a [valid](https://jsonlint.com/) JSON payload:
```json
{
    "text": "hola"
}
```

**Comment by Kikobeats** [comment]
Thanks!
