### ISSUE TITLE
Considerations

### ISSUE THREAD

**Issue by ghost** [amio/marked#3]
Heya there! :) :tada: 

I've notice that you occupied all of `md.now.sh`, `marked.now.sh` and `markdown.now.sh`... could you consider removing some of them? It just not make sense, probably only `marked.now.sh` should remain, since you are using `marked` npm package.

I have some ideas in the head, which are similar like here.

**Comment by amio** [comment]
Hi @olstenlarck thanks for reaching out
I would love to handover `md` or `markdown` to you if you have something cool & suit it, would you share your idea here? Or if you have made some progress, the domain won't be a problem :D

**Comment by amio** [comment]
Close due to inactivity.
